// <auto-generated />
namespace API_MediBridge.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class doctorTableModelBuilder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(doctorTableModelBuilder));
        
        string IMigrationMetadata.Id
        {
            get { return "202311111315221_doctorTableModelBuilder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
